import { useQuery } from "@tanstack/react-query";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { Alert } from "../../components/ui/Alert";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { userErrorMessage } from "../../lib/api-client";
import { getTenderCalendar, getTenderDashboard, getTenderPipeline, listMyTenders, type Tender, type TenderStatus } from "../../services/tenders.service";

type Mode = "dashboard" | "mine" | "calendar" | "pipeline";
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value));
const statusTone = (status: string): "blue" | "green" | "amber" | "red" | "slate" => ["AWARDED"].includes(status) ? "green" : ["LOST", "NO_BID", "CANCELLED"].includes(status) ? "red" : ["UNDER_REVIEW", "BID_DECISION_PENDING"].includes(status) ? "amber" : "blue";
const stages: Array<[string, TenderStatus[]]> = [["Registered / Review", ["DRAFT", "REGISTERED", "UNDER_REVIEW"]], ["Bid Decision", ["BID_DECISION_PENDING", "BID_APPROVED"]], ["Preparing", ["PREPARING"]], ["Ready", ["READY_FOR_SUBMISSION"]], ["Submitted", ["SUBMITTED"]], ["Evaluation", ["CLARIFICATION", "TECHNICAL_EVALUATION", "COMMERCIAL_EVALUATION"]], ["Negotiation", ["NEGOTIATION"]], ["Outcomes", ["AWARDED", "LOST", "NO_BID", "CANCELLED"]]];

export function TenderOperationsPage({ mode }: { mode: Mode }) {
  const { companyId = "" } = useParams(); const [params, setParams] = useSearchParams();
  const search = params.get("search") ?? ""; const status = params.get("status") ?? "";
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); next.set("page", "1"); setParams(next); };
  const query = { page: Number(params.get("page") || 1), limit: 20, search, status: status || undefined, priority: params.get("priority") || undefined, sortBy: params.get("sortBy") || "closingDate", sortOrder: params.get("sortOrder") || "asc" };
  const dashboard = useQuery({ queryKey: ["tender-dashboard", companyId], queryFn: async () => (await getTenderDashboard(companyId)).data, enabled: Boolean(companyId && mode === "dashboard") });
  const mine = useQuery({ queryKey: ["my-tenders", companyId, params.toString()], queryFn: async () => (await listMyTenders(companyId, query)).data, enabled: Boolean(companyId && mode === "mine") });
  const rangeStart = new Date(); rangeStart.setDate(1); const rangeEnd = new Date(rangeStart); rangeEnd.setMonth(rangeEnd.getMonth() + 1); rangeEnd.setDate(0);
  const calendar = useQuery({ queryKey: ["tender-calendar", companyId, rangeStart.toISOString().slice(0, 10), rangeEnd.toISOString().slice(0, 10)], queryFn: async () => (await getTenderCalendar(companyId, rangeStart.toISOString(), rangeEnd.toISOString())).data, enabled: Boolean(companyId && mode === "calendar") });
  const pipeline = useQuery({ queryKey: ["tender-pipeline", companyId], queryFn: async () => (await getTenderPipeline(companyId, { limit: 100 })).data, enabled: Boolean(companyId && mode === "pipeline") });
  const renderTender = (tender: Tender) => <Link key={tender.id} to={`/companies/${companyId}/tenders/${tender.id}`} className="block rounded-md border border-slate-200 p-3 hover:bg-slate-50"><p className="text-xs font-medium text-primary-700">{tender.tenderNumber}</p><p className="truncate font-medium">{tender.title}</p><p className="mt-1 text-xs text-slate-500">{tender.clientCompany?.name ?? "Client"} · {date(tender.closingDate)}</p><div className="mt-2"><Badge tone={statusTone(tender.status)}>{label(tender.status)}</Badge></div></Link>;
  return <div className="space-y-5"><PageHeader title={mode === "dashboard" ? "Tender Dashboard" : mode === "mine" ? "My Tenders" : mode === "calendar" ? "Tender Calendar" : "Tender Pipeline"} description={mode === "dashboard" ? "Operational Tender intelligence and deadline visibility." : undefined} actions={<Link to={`/companies/${companyId}/tenders`}><Button variant="secondary">All Tenders</Button></Link>} />
    {mode === "dashboard" ? <>{dashboard.isLoading ? <p className="text-sm text-slate-500">Loading Tender Dashboard…</p> : null}{dashboard.isError ? <Alert>{userErrorMessage(dashboard.error)}</Alert> : null}{dashboard.data ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Active Tenders", dashboard.data.activeCount], ["Due Today", dashboard.data.dueToday], ["Due This Week", dashboard.data.dueThisWeek], ["Bid Decision Pending", dashboard.data.byStatus.BID_DECISION_PENDING ?? 0], ["Preparing", dashboard.data.byStatus.PREPARING ?? 0], ["Ready for Submission", dashboard.data.byStatus.READY_FOR_SUBMISSION ?? 0], ["Submitted", dashboard.data.byStatus.SUBMITTED ?? 0], ["Under Evaluation", (dashboard.data.byStatus.TECHNICAL_EVALUATION ?? 0) + (dashboard.data.byStatus.COMMERCIAL_EVALUATION ?? 0)], ["Negotiation", dashboard.data.byStatus.NEGOTIATION ?? 0], ["Awarded", dashboard.data.outcomes.AWARDED ?? 0], ["Lost", dashboard.data.outcomes.LOST ?? 0], ["Win Rate", dashboard.data.winRate === null ? "—" : `${dashboard.data.winRate}%`]].map(([name, value]) => <div key={String(name)} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-slate-500">{name}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Next 10 upcoming Tender deadlines</h2><div className="mt-4 space-y-2">{dashboard.data.upcoming.map(renderTender)}{!dashboard.data.upcoming.length ? <p className="text-sm text-slate-500">No Tender data is available for the selected period.</p> : null}</div></section></> : null}</> : null}
    {mode === "mine" ? <><div className="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:grid-cols-3"><Input label="Search" value={search} onChange={(event) => update("search", event.target.value)} /><Select label="Status" value={status} onChange={(event) => update("status", event.target.value)} options={[{ value: "", label: "All statuses" }, ...["DRAFT", "UNDER_REVIEW", "BID_DECISION_PENDING", "PREPARING", "READY_FOR_SUBMISSION", "SUBMITTED"].map((item) => ({ value: item, label: label(item) }))]} /><Select label="Priority" value={params.get("priority") ?? ""} onChange={(event) => update("priority", event.target.value)} options={[{ value: "", label: "All priorities" }, ...["LOW", "MEDIUM", "HIGH", "URGENT", "CRITICAL"].map((item) => ({ value: item, label: label(item) }))]} /></div>{mine.isLoading ? <p>Loading your Tenders…</p> : null}{mine.isError ? <Alert>{userErrorMessage(mine.error)}</Alert> : null}<div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(mine.data ?? []).map(renderTender)}</div>{!mine.isLoading && !mine.data?.length ? <p className="text-sm text-slate-500">You currently have no assigned Tenders.</p> : null}</> : null}
    {mode === "calendar" ? <>{calendar.isLoading ? <p>Loading Tender Calendar…</p> : null}{calendar.isError ? <Alert>{userErrorMessage(calendar.error)}</Alert> : null}<div className="space-y-3">{(calendar.data ?? []).map((event) => <Link key={event.id} to={`/companies/${companyId}/tenders/${event.tenderId}`} className="block rounded-lg border border-slate-200 bg-white p-4 hover:bg-slate-50"><p className="font-medium">{date(event.start)} · {label(event.eventType)}</p><p className="text-sm text-slate-600">{event.tenderNumber} · {event.title}</p></Link>)}</div>{!calendar.isLoading && !calendar.data?.length ? <p className="text-sm text-slate-500">No Tender events for this period.</p> : null}</> : null}
    {mode === "pipeline" ? <>{pipeline.isLoading ? <p>Loading Tender Pipeline…</p> : null}{pipeline.isError ? <Alert>{userErrorMessage(pipeline.error)}</Alert> : null}<div className="grid gap-4 xl:grid-cols-4">{stages.map(([name, statuses]) => <section key={name} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><h2 className="mb-3 text-sm font-semibold">{name}</h2><div className="space-y-2">{(pipeline.data ?? []).filter((item) => statuses.includes(item.status)).map(renderTender)}{!(pipeline.data ?? []).some((item) => statuses.includes(item.status)) ? <p className="text-xs text-slate-500">No Tenders in this stage.</p> : null}</div></section>)}</div></> : null}
  </div>;
}
