import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, FileText, MapPin, Pencil, Target, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useToast } from '../../components/feedback/Toast';
import { ActivityPanel } from '../../components/crm/ActivityPanel';
import { Alert } from '../../components/ui/Alert';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { PageHeader } from '../../components/ui/PageHeader';
import { Select } from '../../components/ui/Select';
import { userErrorMessage } from '../../lib/api-client';
import { addLeadAttachment, addLeadNote, assignLead, changeLeadStatus, deleteLead, deleteLeadNote, getLead, getLeadAssignees, getLeadCatalog, getLeadTimeline, type LeadStatus } from '../../services/crm.service';

const statusLabel = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, (x) => x.toUpperCase());
const tone = (status: string): 'blue' | 'green' | 'amber' | 'red' | 'slate' => status === 'QUALIFIED' || status === 'CONVERTED' ? 'green' : status === 'LOST' ? 'red' : status === 'NEW' ? 'blue' : status === 'CONTACTED' || status === 'ON_HOLD' ? 'amber' : 'slate';
const panel = 'rounded-lg border border-slate-200 bg-white p-5';
const field = (label: string, value?: string | null) => <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value || '—'}</dd></div>;

export function LeadDetailPage() {
  const { companyId = '', leadId = '' } = useParams(); const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast();
  const [note, setNote] = useState(''); const [fileId, setFileId] = useState(''); const [fileTitle, setFileTitle] = useState('');
  const lead = useQuery({ queryKey: ['lead', companyId, leadId], queryFn: async () => (await getLead(companyId, leadId)).data, enabled: Boolean(companyId && leadId) });
  const timeline = useQuery({ queryKey: ['lead-timeline', companyId, leadId], queryFn: async () => (await getLeadTimeline(companyId, leadId)).data, enabled: Boolean(companyId && leadId) });
  const assignees = useQuery({ queryKey: ['lead-assignees', companyId], queryFn: async () => (await getLeadAssignees(companyId)).data, enabled: Boolean(companyId) });
  const catalog = useQuery({ queryKey: ['lead-catalog', companyId], queryFn: async () => (await getLeadCatalog(companyId)).data, enabled: Boolean(companyId) });
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['lead', companyId, leadId] }), qc.invalidateQueries({ queryKey: ['lead-timeline', companyId, leadId] }), qc.invalidateQueries({ queryKey: ['leads', companyId] }), qc.invalidateQueries({ queryKey: ['lead-dashboard', companyId] })]); };
  const action = useMutation({ mutationFn: async (job: () => Promise<unknown>) => job(), onSuccess: async () => { await refresh(); toast.success('Lead updated.'); }, onError: (error) => toast.error(userErrorMessage(error)) });
  const addNote = () => { if (!note.trim()) return; action.mutate(async () => { await addLeadNote(companyId, leadId, note); setNote(''); }); };
  const addAttachment = () => { if (!fileId.trim()) return; action.mutate(async () => { await addLeadAttachment(companyId, leadId, { fileId, title: fileTitle || undefined }); setFileId(''); setFileTitle(''); }); };
  const remove = () => { if (!window.confirm('Archive this lead? It will no longer appear in CRM lists.')) return; action.mutate(async () => { await deleteLead(companyId, leadId); navigate(`/companies/${companyId}/crm/leads`); }); };
  if (lead.isLoading) return <p className="text-sm text-slate-500">Loading lead…</p>;
  if (lead.isError || !lead.data) return <Alert>{userErrorMessage(lead.error)}</Alert>;
  const x = lead.data;
  return <div>
    <Link to={`/companies/${companyId}/crm/leads`} className="mb-3 inline-flex items-center gap-1 text-sm text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Back to leads</Link>
    <PageHeader title={x.name} description={`${x.leadNumber} · Last activity ${new Date(x.lastActivityAt).toLocaleString()}`} actions={<><Link to={`/companies/${companyId}/crm/leads/${leadId}/edit`}><Button variant="secondary"><Pencil className="h-4 w-4" />Edit</Button></Link><Button variant="danger" onClick={remove}><Trash2 className="h-4 w-4" />Archive</Button></>} />
    {action.isError ? <div className="mb-4"><Alert>{userErrorMessage(action.error)}</Alert></div> : null}
    <div className="mb-5 grid gap-4 lg:grid-cols-[2fr_1fr]">
      <section className={panel}><div className="mb-4 flex flex-wrap items-center gap-2"><Badge tone={tone(x.status)}>{statusLabel(x.status)}</Badge><Badge tone={x.priority === 'URGENT' ? 'red' : x.priority === 'HIGH' ? 'amber' : 'slate'}>{x.priority} priority</Badge></div><dl className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{field('Lead type', x.leadType.name)}{field('Lead source', x.leadSource.name)}{field('Estimated value', x.estimatedValue ? `${x.currency} ${Number(x.estimatedValue).toLocaleString()}` : null)}{field('Expected close', x.expectedClosingDate?.slice(0, 10))}{field('Assigned to', x.assignedTo ? `${x.assignedTo.user.firstName} ${x.assignedTo.user.lastName}` : 'Unassigned')}{field('Created', new Date(x.createdAt).toLocaleDateString())}</dl></section>
      <section className={panel}><h2 className="mb-3 font-semibold text-slate-900">Controls</h2><div className="space-y-3">{x.status === 'QUALIFIED' ? <Link to={`/companies/${companyId}/crm/opportunities/new?leadId=${leadId}`}><Button><Target className="h-4 w-4" />Convert to opportunity</Button></Link> : x.status === 'CONVERTED' ? <Alert tone="info">This lead has been converted. See the related opportunity from its timeline.</Alert> : null}<Select label="Status" value={x.status} options={(catalog.data?.statuses ?? []).map((v) => ({ value: v, label: statusLabel(v) }))} onChange={(e) => action.mutate(() => changeLeadStatus(companyId, leadId, e.target.value as LeadStatus))} /><Select label="Assigned to" value={x.assignedTo?.id ?? ''} options={[{ value: '', label: 'Unassigned' }, ...(assignees.data ?? []).map((a) => ({ value: a.id, label: `${a.user.firstName} ${a.user.lastName}` }))]} onChange={(e) => action.mutate(() => assignLead(companyId, leadId, e.target.value || undefined))} /></div></section>
    </div>
    <div className="grid gap-5 lg:grid-cols-2">
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Contact information</h2><div className="mb-4 grid gap-3 sm:grid-cols-2">{x.crmCompany ? <Link to={`/companies/${companyId}/crm/companies/${x.crmCompany.id}`} className="rounded-md border border-primary-200 bg-primary-50 p-3 text-sm font-medium text-primary-800">Company master: {x.crmCompany.name}</Link> : <div className="rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-500">No CRM company linked</div>}{x.crmContact ? <Link to={`/companies/${companyId}/crm/contacts/${x.crmContact.id}`} className="rounded-md border border-primary-200 bg-primary-50 p-3 text-sm font-medium text-primary-800">Contact master: {x.crmContact.firstName} {x.crmContact.lastName}</Link> : <div className="rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-500">No CRM contact linked</div>}</div><dl className="grid gap-4 sm:grid-cols-2">{field('Company snapshot', x.organizationName)}{field('Contact snapshot', x.contactPerson)}{field('Phone', x.phone)}{field('Alternate phone', x.alternatePhone)}{field('Email', x.email)}{field('Website', x.website)}{field('Client address', x.address)}{field('City', x.city)}</dl></section>
      <section className={panel}><h2 className="mb-4 flex items-center gap-2 font-semibold text-slate-900"><MapPin className="h-4 w-4" />Potential project</h2><dl className="grid gap-4 sm:grid-cols-2">{field('Project location', x.projectLocation)}{field('Project city', x.projectCity)}{field('Area', x.projectArea)}{field('Coordinates', x.latitude && x.longitude ? `${x.latitude}, ${x.longitude}` : null)}</dl>{x.description ? <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Description</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{x.description}</p></div> : null}</section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Internal notes</h2><div className="flex gap-2"><textarea aria-label="New internal note" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add an internal note…" className="min-h-20 flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm" /><Button disabled={!note.trim() || action.isPending} onClick={addNote}>Add note</Button></div><div className="mt-4 space-y-3">{x.notes?.map((n) => <article key={n.id} className="rounded-md bg-slate-50 p-3"><p className="whitespace-pre-wrap text-sm text-slate-800">{n.note}</p><div className="mt-2 flex items-center justify-between"><time className="text-xs text-slate-500">{new Date(n.createdAt).toLocaleString()}</time><Button variant="ghost" className="px-2 py-1 text-red-700" onClick={() => action.mutate(() => deleteLeadNote(companyId, leadId, n.id))}>Delete</Button></div></article>)}{!x.notes?.length ? <p className="text-sm text-slate-500">No internal notes yet.</p> : null}</div></section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Attachments</h2><Alert tone="info">Attach an existing secure FileObject by ID. Upload continues to use the ERP storage pipeline.</Alert><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label="File ID" placeholder="File UUID" value={fileId} onChange={(e) => setFileId(e.target.value)} /><Input aria-label="Attachment title" placeholder="Title (optional)" value={fileTitle} onChange={(e) => setFileTitle(e.target.value)} /><Button disabled={!fileId || action.isPending} onClick={addAttachment}>Attach</Button></div><div className="mt-4 space-y-2">{x.attachments?.map((a) => <a key={a.id} href={a.file.publicUrl || '#'} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-md border border-slate-200 p-3 hover:bg-slate-50"><FileText className="h-5 w-5 text-slate-500" /><span className="min-w-0"><span className="block truncate text-sm font-medium">{a.title || a.file.originalName}</span><span className="text-xs text-slate-500">{a.file.mimeType}</span></span></a>)}{!x.attachments?.length ? <p className="text-sm text-slate-500">No attachments yet.</p> : null}</div></section>
    </div>
    <div className="mt-5"><ActivityPanel companyId={companyId} relatedType="LEAD" relatedId={leadId} /></div>
    <section className={`${panel} mt-5`}><h2 className="mb-4 font-semibold text-slate-900">Timeline</h2><ol className="relative ml-2 border-l border-slate-200 pl-5">{timeline.data?.map((event) => <li key={event.id} className="relative mb-5 last:mb-0"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-primary-600 ring-4 ring-white" /><p className="text-sm font-medium text-slate-900">{event.action.replace('CRM.Lead.', '').replaceAll(/([A-Z])/g, ' $1').trim()}</p><p className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}{event.user ? ` · ${event.user.firstName} ${event.user.lastName}` : ''}</p></li>)}{!timeline.data?.length ? <p className="text-sm text-slate-500">No activity recorded.</p> : null}</ol></section>
  </div>;
}
