import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { FormErrorSummary } from '../../components/feedback/FormErrorSummary';
import { useToast } from '../../components/feedback/Toast';
import { Alert } from '../../components/ui/Alert';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { PageHeader } from '../../components/ui/PageHeader';
import { Select } from '../../components/ui/Select';
import { ApiError, userErrorMessage } from '../../lib/api-client';
import { applyApiFieldErrors } from '../../lib/errors/apply-field-errors';
import { checkLeadDuplicates, createLead, getLead, getLeadAssignees, getLeadCatalog, listCrmCompanies, listCrmContacts, updateLead, type LeadInput } from '../../services/crm.service';

const schema = z.object({
  name: z.string().min(2, 'Lead Name is required.').max(255), leadTypeId: z.string().uuid('Please select Lead Type.'), leadSourceId: z.string().uuid('Please select Lead Source.'),
  organizationName: z.string().max(255).optional(), contactPerson: z.string().max(200).optional(), phone: z.string().max(32).optional(), alternatePhone: z.string().max(32).optional(),
  crmCompanyId: z.string().uuid().optional().or(z.literal('')), crmContactId: z.string().uuid().optional().or(z.literal('')),
  email: z.string().email('Please enter a valid email address.').optional().or(z.literal('')), website: z.string().url('Enter a full URL including https://').optional().or(z.literal('')),
  address: z.string().max(500).optional(), city: z.string().max(120).optional(), projectLocation: z.string().max(500).optional(), projectCity: z.string().max(120).optional(), projectArea: z.string().max(160).optional(),
  latitude: z.coerce.number().min(-90).max(90).optional().or(z.nan()), longitude: z.coerce.number().min(-180).max(180).optional().or(z.nan()),
  estimatedValue: z.coerce.number().min(0, 'Please enter a valid project value.').optional().or(z.nan()), currency: z.string().regex(/^[A-Z]{3}$/, 'Use a three-letter currency code.'),
  expectedClosingDate: z.string().optional(), assignedToId: z.string().uuid().optional().or(z.literal('')), priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']), description: z.string().optional(),
});
type Values = z.infer<typeof schema>;
const section = 'rounded-lg border border-slate-200 bg-white p-5';

export function LeadFormPage() {
  const { companyId = '', leadId } = useParams(); const edit = Boolean(leadId); const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast();
  const [duplicates, setDuplicates] = useState<Array<{ id: string; leadNumber: string; name: string }>>([]);
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name: '', leadTypeId: '', leadSourceId: '', crmCompanyId: '', crmContactId: '', organizationName: '', contactPerson: '', phone: '', alternatePhone: '', email: '', website: '', address: '', city: '', projectLocation: '', projectCity: '', projectArea: '', currency: 'USD', expectedClosingDate: '', assignedToId: '', priority: 'MEDIUM', description: '' } });
  const catalog = useQuery({ queryKey: ['lead-catalog', companyId], queryFn: async () => (await getLeadCatalog(companyId)).data, enabled: Boolean(companyId) });
  const assignees = useQuery({ queryKey: ['lead-assignees', companyId], queryFn: async () => (await getLeadAssignees(companyId)).data, enabled: Boolean(companyId) });
  const crmCompanies = useQuery({ queryKey: ['crm-company-options', companyId], queryFn: async () => (await listCrmCompanies(companyId, { limit: 100, sortBy: 'name', sortOrder: 'asc' })).data, enabled: Boolean(companyId) });
  const selectedCrmCompanyId = form.watch('crmCompanyId');
  const crmContacts = useQuery({ queryKey: ['crm-contact-options', companyId, selectedCrmCompanyId], queryFn: async () => (await listCrmContacts(companyId, { limit: 100, crmCompanyId: selectedCrmCompanyId || undefined, sortBy: 'firstName', sortOrder: 'asc' })).data, enabled: Boolean(companyId) });
  const lead = useQuery({ queryKey: ['lead', companyId, leadId], queryFn: async () => (await getLead(companyId, leadId!)).data, enabled: edit });
  useEffect(() => { if (!edit && catalog.data?.defaultCurrency) form.setValue('currency', catalog.data.defaultCurrency); }, [catalog.data, edit, form]);
  useEffect(() => { const x = lead.data; if (!x) return; form.reset({ name: x.name, leadTypeId: x.leadType.id, leadSourceId: x.leadSource.id, crmCompanyId: x.crmCompany?.id ?? '', crmContactId: x.crmContact?.id ?? '', organizationName: x.organizationName ?? '', contactPerson: x.contactPerson ?? '', phone: x.phone ?? '', alternatePhone: x.alternatePhone ?? '', email: x.email ?? '', website: x.website ?? '', address: x.address ?? '', city: x.city ?? '', projectLocation: x.projectLocation ?? '', projectCity: x.projectCity ?? '', projectArea: x.projectArea ?? '', latitude: x.latitude ? Number(x.latitude) : undefined, longitude: x.longitude ? Number(x.longitude) : undefined, estimatedValue: x.estimatedValue ? Number(x.estimatedValue) : undefined, currency: x.currency, expectedClosingDate: x.expectedClosingDate?.slice(0, 10) ?? '', assignedToId: x.assignedTo?.id ?? '', priority: x.priority, description: x.description ?? '' }); }, [lead.data, form]);
  const clean = (v: Values, overrideDuplicate = false): LeadInput => ({ ...v, crmCompanyId: v.crmCompanyId || undefined, crmContactId: v.crmContactId || undefined, email: v.email || undefined, website: v.website || undefined, assignedToId: v.assignedToId || undefined, expectedClosingDate: v.expectedClosingDate || undefined, latitude: Number.isFinite(v.latitude) ? v.latitude : undefined, longitude: Number.isFinite(v.longitude) ? v.longitude : undefined, estimatedValue: Number.isFinite(v.estimatedValue) ? v.estimatedValue : undefined, overrideDuplicate });
  const mutation = useMutation({ mutationFn: ({ values, override }: { values: Values; override: boolean }) => edit ? updateLead(companyId, leadId!, clean(values, override)) : createLead(companyId, clean(values, override)), onSuccess: async (response) => { await qc.invalidateQueries({ queryKey: ['leads', companyId] }); await qc.invalidateQueries({ queryKey: ['lead-dashboard', companyId] }); toast.success(edit ? 'Lead changes saved.' : 'Lead created.'); navigate(`/companies/${companyId}/crm/leads/${response.data.id}`); }, onError: (error) => applyApiFieldErrors(form.setError, error instanceof ApiError ? error : {}) });
  const submit = async (values: Values, override = false) => { if (!override) { const response = await checkLeadDuplicates(companyId, { email: values.email || undefined, phone: values.phone || undefined, organizationName: values.organizationName || undefined, contactPerson: values.contactPerson || undefined, excludeLeadId: leadId }); if (response.data.length) { setDuplicates(response.data); return; } } mutation.mutate({ values, override }); };
  const errors = Object.values(form.formState.errors).map((x) => x?.message).filter((x): x is string => Boolean(x));
  return <div><PageHeader title={edit ? 'Edit lead' : 'Add lead'} description="Capture enough information to qualify potential construction work. Lead number is generated securely when saved." />
    {mutation.isError ? <div className="mb-4"><Alert>{userErrorMessage(mutation.error)}</Alert></div> : null}
    {duplicates.length ? <div className="mb-4"><Alert tone="info"><p className="font-medium">Possible duplicate lead found.</p><ul className="mt-1 list-disc pl-5">{duplicates.map((x) => <li key={x.id}>{x.leadNumber} · {x.name}</li>)}</ul><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={() => setDuplicates([])}>Review form</Button><Button onClick={() => void form.handleSubmit((v) => submit(v, true))()}>Continue anyway</Button></div></Alert></div> : null}
    <form noValidate className="space-y-5" onSubmit={form.handleSubmit((v) => void submit(v))}><FormErrorSummary messages={errors} />
      <section className={section}><h2 className="mb-4 font-semibold text-slate-900">Lead overview</h2><div className="grid gap-4 md:grid-cols-2"><Input label="Lead name *" error={form.formState.errors.name?.message} {...form.register('name')} /><Select label="Priority" options={['LOW', 'MEDIUM', 'HIGH', 'URGENT'].map((x) => ({ value: x, label: x }))} {...form.register('priority')} /><Select label="Lead type *" error={form.formState.errors.leadTypeId?.message} options={[{ value: '', label: 'Select lead type' }, ...(catalog.data?.types ?? []).map((x) => ({ value: x.id, label: x.name }))]} {...form.register('leadTypeId')} /><Select label="Lead source *" error={form.formState.errors.leadSourceId?.message} options={[{ value: '', label: 'Select lead source' }, ...(catalog.data?.sources ?? []).map((x) => ({ value: x.id, label: x.name }))]} {...form.register('leadSourceId')} /><Select label="Assigned to" options={[{ value: '', label: 'Unassigned' }, ...(assignees.data ?? []).map((x) => ({ value: x.id, label: `${x.user.firstName} ${x.user.lastName}` }))]} {...form.register('assignedToId')} /></div></section>
      <section className={section}><h2 className="mb-4 font-semibold text-slate-900">Contact information</h2><Alert tone="info">Link a CRM master record when known. Snapshot fields remain available to preserve historical enquiry data.</Alert><div className="mt-4 grid gap-4 md:grid-cols-2"><Select label="CRM company" options={[{ value: '', label: 'Not linked' }, ...(crmCompanies.data ?? []).map((x) => ({ value: x.id, label: x.name }))]} {...form.register('crmCompanyId')} /><Select label="CRM contact" options={[{ value: '', label: 'Not linked' }, ...(crmContacts.data ?? []).map((x) => ({ value: x.id, label: `${x.firstName} ${x.lastName ?? ''}${x.crmCompany ? ` · ${x.crmCompany.name}` : ''}` }))]} {...form.register('crmContactId')} /><Input label="Company snapshot" {...form.register('organizationName')} /><Input label="Contact snapshot" {...form.register('contactPerson')} /><Input label="Phone" {...form.register('phone')} /><Input label="Alternate phone" {...form.register('alternatePhone')} /><Input label="Email" type="email" error={form.formState.errors.email?.message} {...form.register('email')} /><Input label="Website" placeholder="https://example.com" error={form.formState.errors.website?.message} {...form.register('website')} /><Input label="Client address" {...form.register('address')} /><Input label="Client city" {...form.register('city')} /></div></section>
      <section className={section}><h2 className="mb-4 font-semibold text-slate-900">Potential project</h2><div className="grid gap-4 md:grid-cols-2"><Input label="Project location" {...form.register('projectLocation')} /><Input label="Project city" {...form.register('projectCity')} /><Input label="Area" {...form.register('projectArea')} /><Input label="Expected closing date" type="date" {...form.register('expectedClosingDate')} /><Input label="Estimated project value" type="number" min="0" step="0.01" error={form.formState.errors.estimatedValue?.message} {...form.register('estimatedValue')} /><Input label="Currency" maxLength={3} error={form.formState.errors.currency?.message} {...form.register('currency')} /><Input label="Latitude (optional)" type="number" step="0.0000001" {...form.register('latitude')} /><Input label="Longitude (optional)" type="number" step="0.0000001" {...form.register('longitude')} /></div><label className="mt-4 block space-y-1.5"><span className="text-sm font-medium text-slate-700">Description / initial requirements</span><textarea className="min-h-28 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" {...form.register('description')} /></label></section>
      <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : edit ? 'Save changes' : 'Create lead'}</Button></div>
    </form>
  </div>;
}
