import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, FileText, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useToast } from '../../components/feedback/Toast';
import { Alert } from '../../components/ui/Alert';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { PageHeader } from '../../components/ui/PageHeader';
import { Select } from '../../components/ui/Select';
import { ActivityPanel } from '../../components/crm/ActivityPanel';
import { userErrorMessage } from '../../lib/api-client';
import {
  addOpportunityAttachment, addOpportunityNote, assignOpportunity, changeOpportunityStage,
  deleteOpportunity, deleteOpportunityAttachment, deleteOpportunityNote, getOpportunity,
  getOpportunityAssignees, getOpportunityCatalog, getOpportunityStageHistory, getOpportunityTimeline,
  markOpportunityLost, markOpportunityWon, reopenOpportunity,
} from '../../services/opportunities.service';

const panel = 'rounded-lg border border-slate-200 bg-white p-5';
const field = (label: string, value?: string | null) => <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value || '—'}</dd></div>;
const statusTone = (status: string): 'blue' | 'green' | 'amber' | 'red' | 'slate' => status === 'WON' ? 'green' : status === 'LOST' ? 'red' : 'blue';
const actionLabel = (action: string) => action.replace('CRM.Opportunity.', '').replaceAll(/([A-Z])/g, ' $1').trim();
type Tab = 'overview' | 'pipeline' | 'activities' | 'notes' | 'documents' | 'timeline';
const tabs: Array<[Tab, string]> = [['overview', 'Overview'], ['pipeline', 'Pipeline & Financial'], ['activities', 'Activities'], ['notes', 'Notes'], ['documents', 'Documents'], ['timeline', 'Timeline']];

export function OpportunityDetailPage() {
  const { companyId = '', opportunityId = '' } = useParams();
  const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast();
  const [tab, setTab] = useState<Tab>('overview');
  const [note, setNote] = useState(''); const [fileId, setFileId] = useState(''); const [fileTitle, setFileTitle] = useState('');
  const [wonDate, setWonDate] = useState(new Date().toISOString().slice(0, 10)); const [finalContractValue, setFinalContractValue] = useState(''); const [winReason, setWinReason] = useState(''); const [competitor, setCompetitor] = useState('');
  const [lostReasonId, setLostReasonId] = useState(''); const [lostDate, setLostDate] = useState(new Date().toISOString().slice(0, 10)); const [lostRemarks, setLostRemarks] = useState('');
  const [reopenReason, setReopenReason] = useState(''); const [stageReason, setStageReason] = useState(''); const [stageTarget, setStageTarget] = useState('');
  const opportunity = useQuery({ queryKey: ['opportunity', companyId, opportunityId], queryFn: async () => (await getOpportunity(companyId, opportunityId)).data, enabled: Boolean(companyId && opportunityId) });
  const catalog = useQuery({ queryKey: ['opportunity-catalog', companyId], queryFn: async () => (await getOpportunityCatalog(companyId)).data, enabled: Boolean(companyId) });
  const assignees = useQuery({ queryKey: ['opportunity-assignees', companyId], queryFn: async () => (await getOpportunityAssignees(companyId)).data, enabled: Boolean(companyId) });
  const timeline = useQuery({ queryKey: ['opportunity-timeline', companyId, opportunityId], queryFn: async () => (await getOpportunityTimeline(companyId, opportunityId)).data, enabled: Boolean(companyId && opportunityId) });
  const stageHistory = useQuery({ queryKey: ['opportunity-stage-history', companyId, opportunityId], queryFn: async () => (await getOpportunityStageHistory(companyId, opportunityId)).data, enabled: Boolean(companyId && opportunityId) });
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['opportunity', companyId, opportunityId] }), qc.invalidateQueries({ queryKey: ['opportunity-timeline', companyId, opportunityId] }), qc.invalidateQueries({ queryKey: ['opportunity-stage-history', companyId, opportunityId] }), qc.invalidateQueries({ queryKey: ['opportunities', companyId] }), qc.invalidateQueries({ queryKey: ['opportunity-dashboard', companyId] }), qc.invalidateQueries({ queryKey: ['opportunity-pipeline', companyId] })]); };
  const action = useMutation({ mutationFn: async (job: () => Promise<unknown>) => job(), onSuccess: async (message?: unknown) => { await refresh(); toast.success(typeof message === 'string' ? message : 'Opportunity updated.'); }, onError: (error) => toast.error(userErrorMessage(error)) });
  const addNote = () => { if (!note.trim()) return; action.mutate(async () => { await addOpportunityNote(companyId, opportunityId, note); setNote(''); return 'Note added.'; }); };
  const addAttachment = () => { if (!fileId.trim()) return; action.mutate(async () => { await addOpportunityAttachment(companyId, opportunityId, { fileId, title: fileTitle || undefined }); setFileId(''); setFileTitle(''); return 'Attachment added.'; }); };
  const remove = () => { if (!window.confirm('Archive this opportunity? It will no longer appear in CRM lists.')) return; action.mutate(async () => { await deleteOpportunity(companyId, opportunityId); navigate(`/companies/${companyId}/crm/opportunities`); }); };
  const submitWon = () => { if (!wonDate || !finalContractValue) return; action.mutate(async () => { await markOpportunityWon(companyId, opportunityId, { wonDate, finalContractValue: Number(finalContractValue), winReason: winReason || undefined, competitor: competitor || undefined }); setWinReason(''); setCompetitor(''); return 'Opportunity marked as won.'; }); };
  const submitLost = () => { if (!lostReasonId || !lostDate) return; action.mutate(async () => { await markOpportunityLost(companyId, opportunityId, { lostReasonId, lostDate, lostRemarks: lostRemarks || undefined }); setLostRemarks(''); return 'Opportunity marked as lost.'; }); };
  const submitReopen = () => { if (!reopenReason.trim()) return; action.mutate(async () => { await reopenOpportunity(companyId, opportunityId, reopenReason); setReopenReason(''); return 'Opportunity reopened.'; }); };
  if (opportunity.isLoading) return <p className="text-sm text-slate-500">Loading opportunity…</p>;
  if (opportunity.isError || !opportunity.data) return <Alert>{userErrorMessage(opportunity.error)}</Alert>;
  const x = opportunity.data;
  const openStages = (catalog.data?.stages ?? []).filter((s) => !s.isWon && !s.isLost);
  const assigneeName = (a?: { user: { firstName: string; lastName: string } } | null) => a ? `${a.user.firstName} ${a.user.lastName}` : 'Unassigned';
  return <div>
    <Link to={`/companies/${companyId}/crm/opportunities`} className="mb-3 inline-flex items-center gap-1 text-sm text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Back to opportunities</Link>
    <PageHeader title={x.name} description={`${x.opportunityNumber} · Last activity ${new Date(x.lastActivityAt).toLocaleString()}`} actions={<><Link to={`/companies/${companyId}/crm/opportunities/${opportunityId}/edit`}><Button variant="secondary"><Pencil className="h-4 w-4" />Edit</Button></Link><Button variant="danger" onClick={remove}><Trash2 className="h-4 w-4" />Archive</Button></>} />
    {action.isError ? <div className="mb-4"><Alert>{userErrorMessage(action.error)}</Alert></div> : null}
    <div className="mb-5 flex flex-wrap items-center gap-2"><Badge tone={statusTone(x.status)}>{x.status === 'WON' ? 'Won' : x.status === 'LOST' ? 'Lost' : 'Open'}</Badge><Badge tone="slate">{x.stage.name} · {x.probability}%</Badge><Badge tone={x.priority === 'URGENT' ? 'red' : x.priority === 'HIGH' ? 'amber' : 'slate'}>{x.priority} priority</Badge>{x.status === 'OPEN' && x.expectedClosingDate && new Date(x.expectedClosingDate) < new Date() ? <Badge tone="red">Closing overdue</Badge> : null}</div>
    <div className="mb-5 flex flex-wrap gap-1 border-b border-slate-200">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`-mb-px rounded-t-md border-b-2 px-4 py-2 text-sm font-medium ${tab === key ? 'border-primary-600 text-primary-700' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{label}</button>)}</div>
    {tab === 'overview' ? <div className="grid gap-5 lg:grid-cols-2">
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Overview</h2><dl className="grid gap-4 sm:grid-cols-2">{field('Opportunity type', x.opportunityType.name)}{field('Source', x.source.name)}{field('Assigned to', assigneeName(x.assignedTo))}{field('Created', new Date(x.createdAt).toLocaleDateString())}{field('Expected close', x.expectedClosingDate?.slice(0, 10))}{field('Expected start', x.expectedStartDate?.slice(0, 10))}{field('Expected completion', x.expectedCompletionDate?.slice(0, 10))}</dl>{x.description ? <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Description</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{x.description}</p></div> : null}</section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Controls</h2>{x.status === 'OPEN' ? <div className="space-y-3"><Select label="Stage" value={stageTarget || x.stage.id} options={openStages.map((s) => ({ value: s.id, label: `${s.name} (${s.probability}%)` }))} onChange={(e) => setStageTarget(e.target.value)} /><Input label="Stage change reason (optional)" value={stageReason} onChange={(e) => setStageReason(e.target.value)} placeholder="Recorded in stage history and audit trail" /><Button variant="secondary" disabled={!stageTarget || stageTarget === x.stage.id || action.isPending} onClick={() => action.mutate(async () => { const target = stageTarget; const reason = stageReason.trim(); setStageTarget(''); setStageReason(''); await changeOpportunityStage(companyId, opportunityId, target, reason || undefined); return 'Stage updated.'; })}>Move stage</Button><Select label="Assigned to" value={x.assignedTo?.id ?? ''} options={[{ value: '', label: 'Unassigned' }, ...(assignees.data ?? []).map((a) => ({ value: a.id, label: `${a.user.firstName} ${a.user.lastName}` }))]} onChange={(e) => action.mutate(() => assignOpportunity(companyId, opportunityId, e.target.value || undefined))} /></div> : null}
        {x.status === 'WON' || x.status === 'LOST' ? <div className="space-y-3"><Alert tone="info">{x.status === 'WON' ? `Won on ${x.wonDate?.slice(0, 10)} with a final contract value of ${x.currency} ${Number(x.finalContractValue ?? 0).toLocaleString()}.` : `Lost on ${x.lostDate?.slice(0, 10)}${x.lostReason ? ` · ${x.lostReason.name}` : ''}.`}</Alert><Input label="Reopen reason *" value={reopenReason} onChange={(e) => setReopenReason(e.target.value)} placeholder="Why is this opportunity active again?" /><Button disabled={!reopenReason.trim() || action.isPending} onClick={submitReopen}>Reopen opportunity</Button></div> : null}
      </section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Company &amp; contact</h2>{x.crmCompany ? <Link to={`/companies/${companyId}/crm/companies/${x.crmCompany.id}`} className="mb-3 block rounded-md border border-primary-200 bg-primary-50 p-3 text-sm font-medium text-primary-800">Company master: {x.crmCompany.name}</Link> : <div className="mb-3 rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-500">No CRM company linked</div>}{x.crmContact ? <Link to={`/companies/${companyId}/crm/contacts/${x.crmContact.id}`} className="block rounded-md border border-primary-200 bg-primary-50 p-3 text-sm font-medium text-primary-800">Contact master: {x.crmContact.firstName} {x.crmContact.lastName}</Link> : <div className="rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-500">No CRM contact linked</div>}</section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Project information</h2><dl className="grid gap-4 sm:grid-cols-2">{field('Project location', x.projectLocation)}{field('City', x.city)}{field('Area', x.area)}</dl>{x.lead ? <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Related lead</p><Link to={`/companies/${companyId}/crm/leads/${x.lead.id}`} className="mt-2 block rounded-md border border-primary-200 bg-primary-50 p-3 text-sm font-medium text-primary-800">{x.lead.leadNumber} · {x.lead.name}</Link></div> : null}</section>
    </div> : null}
    {tab === 'pipeline' ? <div className="grid gap-5 lg:grid-cols-2">
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Financial</h2><dl className="grid gap-4 sm:grid-cols-2">{field('Estimated contract value', x.estimatedContractValue ? `${x.currency} ${Number(x.estimatedContractValue).toLocaleString()}` : null)}{field('Probability', `${x.probability}%`)}{field('Weighted value', x.weightedValue ? `${x.currency} ${Number(x.weightedValue).toLocaleString()}` : '—')}{field('Final contract value', x.finalContractValue ? `${x.currency} ${Number(x.finalContractValue).toLocaleString()}` : null)}{field('Win reason', x.winReason)}{field('Competitor', x.competitor)}{field('Lost remarks', x.lostRemarks)}</dl></section>
      <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Close opportunity</h2>{x.status === 'OPEN' ? <div className="space-y-5">
        <div className="rounded-md border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-medium text-emerald-900">Mark as won</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Won date *" type="date" value={wonDate} onChange={(e) => setWonDate(e.target.value)} /><Input label="Final contract value *" type="number" min="0" step="0.01" value={finalContractValue} onChange={(e) => setFinalContractValue(e.target.value)} /><Input label="Win reason" value={winReason} onChange={(e) => setWinReason(e.target.value)} /><Input label="Competitor" value={competitor} onChange={(e) => setCompetitor(e.target.value)} /></div><Button className="mt-3" disabled={!wonDate || !finalContractValue || action.isPending} onClick={submitWon}>Mark as won</Button></div>
        <div className="rounded-md border border-red-200 bg-red-50 p-4"><h3 className="font-medium text-red-900">Mark as lost</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select label="Lost reason *" value={lostReasonId} onChange={(e) => setLostReasonId(e.target.value)} options={[{ value: '', label: 'Select lost reason' }, ...(catalog.data?.lostReasons ?? []).map((r) => ({ value: r.id, label: r.name }))]} /><Input label="Lost date *" type="date" value={lostDate} onChange={(e) => setLostDate(e.target.value)} /></div><label className="mt-3 block space-y-1.5"><span className="text-sm font-medium text-red-900">Remarks</span><textarea className="min-h-20 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" value={lostRemarks} onChange={(e) => setLostRemarks(e.target.value)} /></label><Button variant="danger" className="mt-3" disabled={!lostReasonId || !lostDate || action.isPending} onClick={submitLost}>Mark as lost</Button></div>
      </div> : <Alert tone="info">This opportunity is {x.status === 'WON' ? 'won' : 'lost'}. Use the Reopen control on the Overview tab to return it to the pipeline.</Alert>}</section>
      <section className={`${panel} lg:col-span-2`}><h2 className="mb-4 font-semibold text-slate-900">Stage history</h2><ol className="relative ml-2 border-l border-slate-200 pl-5">{(stageHistory.data ?? []).map((h) => <li key={h.id} className="relative mb-5 last:mb-0"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-primary-600 ring-4 ring-white" /><p className="text-sm font-medium text-slate-900">{h.fromStage ? `${h.fromStage.name} → ` : 'Started at '}{h.toStage.name}</p>{h.reason ? <p className="text-xs text-slate-600">{h.reason}</p> : null}<p className="text-xs text-slate-500">{new Date(h.changedAt).toLocaleString()}{h.changedBy ? ` · ${h.changedBy.user.firstName} ${h.changedBy.user.lastName}` : ''}</p></li>)}{!stageHistory.data?.length ? <p className="text-sm text-slate-500">No stage changes recorded.</p> : null}</ol></section>
    </div> : null}
    {tab === 'activities' ? <ActivityPanel companyId={companyId} relatedType="OPPORTUNITY" relatedId={opportunityId} /> : null}
    {tab === 'notes' ? <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Internal notes</h2><div className="flex gap-2"><textarea aria-label="New internal note" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add an internal note…" className="min-h-20 flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm" /><Button disabled={!note.trim() || action.isPending} onClick={addNote}>Add note</Button></div><div className="mt-4 space-y-3">{(x.notes ?? []).map((n) => <article key={n.id} className="rounded-md bg-slate-50 p-3"><p className="whitespace-pre-wrap text-sm text-slate-800">{n.note}</p><div className="mt-2 flex items-center justify-between"><time className="text-xs text-slate-500">{new Date(n.createdAt).toLocaleString()}</time><Button variant="ghost" className="px-2 py-1 text-red-700" disabled={action.isPending} onClick={() => action.mutate(() => deleteOpportunityNote(companyId, opportunityId, n.id))}>Delete</Button></div></article>)}{!x.notes?.length ? <p className="text-sm text-slate-500">No internal notes yet.</p> : null}</div></section> : null}
    {tab === 'documents' ? <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Documents</h2><Alert tone="info">Attach an existing secure FileObject by ID. Upload continues to use the ERP storage pipeline.</Alert><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label="File ID" placeholder="File UUID" value={fileId} onChange={(e) => setFileId(e.target.value)} /><Input aria-label="Attachment title" placeholder="Title (optional)" value={fileTitle} onChange={(e) => setFileTitle(e.target.value)} /><Button disabled={!fileId || action.isPending} onClick={addAttachment}>Attach</Button></div><div className="mt-4 space-y-2">{(x.attachments ?? []).map((a) => <div key={a.id} className="flex items-center gap-3 rounded-md border border-slate-200 p-3"><a href={a.file.publicUrl || '#'} target="_blank" rel="noreferrer" className="flex min-w-0 flex-1 items-center gap-3 hover:bg-slate-50"><FileText className="h-5 w-5 shrink-0 text-slate-500" /><span className="min-w-0"><span className="block truncate text-sm font-medium">{a.title || a.file.originalName}</span><span className="text-xs text-slate-500">{a.file.mimeType}</span></span></a><Button variant="ghost" className="px-2 py-1 text-xs text-red-700" disabled={action.isPending} onClick={() => action.mutate(() => deleteOpportunityAttachment(companyId, opportunityId, a.id))}>Remove</Button></div>)}{!x.attachments?.length ? <p className="text-sm text-slate-500">No documents attached yet.</p> : null}</div></section> : null}
    {tab === 'timeline' ? <section className={panel}><h2 className="mb-4 font-semibold text-slate-900">Timeline</h2><ol className="relative ml-2 border-l border-slate-200 pl-5">{(timeline.data ?? []).map((event) => <li key={event.id} className="relative mb-5 last:mb-0"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-primary-600 ring-4 ring-white" /><p className="text-sm font-medium text-slate-900">{actionLabel(event.action)}</p><p className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}{event.user ? ` · ${event.user.firstName} ${event.user.lastName}` : ''}</p></li>)}{!timeline.data?.length ? <p className="text-sm text-slate-500">No activity recorded.</p> : null}</ol></section> : null}
  </div>;
}
