import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useToast } from '../../components/feedback/Toast';
import { Alert } from '../../components/ui/Alert';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { PageHeader } from '../../components/ui/PageHeader';
import { Select } from '../../components/ui/Select';
import { userErrorMessage } from '../../lib/api-client';
import { checkCrmCompanyDuplicates, checkCrmContactDuplicates, createCrmCompany, createCrmContact, getCrmCompany, getCrmContact, getPartyAssignees, getPartyCatalog, listCrmCompanies, updateCrmCompany, updateCrmContact, type CrmCompanyInput, type CrmContactInput } from '../../services/crm.service';

type FormState = any;
const blankCompany: FormState = { name: '', legalName: '', registrationNumber: '', taxNumber: '', industry: '', website: '', email: '', phone: '', alternatePhone: '', address: '', city: '', country: '', postalCode: '', description: '', status: 'PROSPECT', assignedToId: '', typeIds: [] };
const blankContact: FormState = { firstName: '', lastName: '', jobTitle: '', department: '', crmCompanyId: '', email: '', alternateEmail: '', phone: '', mobile: '', whatsapp: '', website: '', address: '', city: '', country: '', linkedin: '', notesText: '', status: 'ACTIVE', assignedToId: '', typeIds: [] };
const panel = 'rounded-lg border border-slate-200 bg-white p-5';

export function PartyFormPage({ kind }: { kind: 'company' | 'contact' }) {
  const { companyId = '', partyId } = useParams(); const edit = Boolean(partyId); const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast();
  const [form, setForm] = useState<FormState>(kind === 'company' ? blankCompany : blankContact); const [error, setError] = useState(''); const [duplicates, setDuplicates] = useState<Array<{ id: string; name?: string; firstName?: string; lastName?: string }>>([]);
  const catalog = useQuery({ queryKey: ['party-catalog', companyId], queryFn: async () => (await getPartyCatalog(companyId)).data, enabled: Boolean(companyId) });
  const assignees = useQuery({ queryKey: ['party-assignees', companyId], queryFn: async () => (await getPartyAssignees(companyId)).data, enabled: Boolean(companyId) });
  const companies = useQuery({ queryKey: ['crm-company-options', companyId], queryFn: async () => (await listCrmCompanies(companyId, { limit: 100, sortBy: 'name', sortOrder: 'asc' })).data, enabled: kind === 'contact' });
  const current = useQuery({ queryKey: ['crm-party', kind, companyId, partyId], queryFn: async () => kind === 'company' ? (await getCrmCompany(companyId, partyId!)).data : (await getCrmContact(companyId, partyId!)).data, enabled: edit });
  useEffect(() => { const x = current.data; if (!x) return; if (kind === 'company' && 'name' in x) setForm({ ...blankCompany, name: x.name, legalName: x.legalName ?? '', registrationNumber: x.registrationNumber ?? '', taxNumber: x.taxNumber ?? '', industry: x.industry ?? '', website: x.website ?? '', email: x.email ?? '', phone: x.phone ?? '', alternatePhone: x.alternatePhone ?? '', address: x.address ?? '', city: x.city ?? '', country: x.country ?? '', postalCode: x.postalCode ?? '', description: x.description ?? '', status: x.status, assignedToId: x.assignedTo?.id ?? '', typeIds: x.types.map((t) => t.type.id) }); else if ('firstName' in x) setForm({ ...blankContact, firstName: x.firstName, lastName: x.lastName ?? '', jobTitle: x.jobTitle ?? '', department: x.department ?? '', crmCompanyId: x.crmCompany?.id ?? '', email: x.email ?? '', alternateEmail: x.alternateEmail ?? '', phone: x.phone ?? '', mobile: x.mobile ?? '', whatsapp: x.whatsapp ?? '', website: x.website ?? '', address: x.address ?? '', city: x.city ?? '', country: x.country ?? '', linkedin: x.linkedin ?? '', notesText: x.notesText ?? '', status: x.status, assignedToId: x.assignedTo?.id ?? '', typeIds: x.types.map((t) => t.type.id) }); }, [current.data, kind]);
  const set = (key: string, value: string) => setForm((x: FormState) => ({ ...x, [key]: value })); const toggle = (id: string) => setForm((x: FormState) => ({ ...x, typeIds: x.typeIds.includes(id) ? x.typeIds.filter((v: string) => v !== id) : [...x.typeIds, id] }));
  const clean = (overrideDuplicate: boolean) => ({ ...Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value === '' ? undefined : value]).filter(([, value]) => value !== undefined)), overrideDuplicate });
  const mutation = useMutation({ mutationFn: async (override: boolean) => { const body = clean(override); if (kind === 'company') return edit ? updateCrmCompany(companyId, partyId!, body as CrmCompanyInput) : createCrmCompany(companyId, body as CrmCompanyInput); return edit ? updateCrmContact(companyId, partyId!, body as CrmContactInput) : createCrmContact(companyId, body as CrmContactInput); }, onSuccess: async (response) => { await qc.invalidateQueries({ queryKey: ['crm-parties'] }); toast.success(`${kind === 'company' ? 'Company' : 'Contact'} saved.`); navigate(`/companies/${companyId}/crm/${kind === 'company' ? 'companies' : 'contacts'}/${response.data.id}`); }, onError: (e) => setError(userErrorMessage(e)) });
  const submit = async (override = false) => { setError(''); if (!(kind === 'company' ? form.name.trim() : form.firstName.trim())) { setError(`${kind === 'company' ? 'Company Name' : 'First Name'} is required.`); return; } if (!override) { const result = kind === 'company' ? await checkCrmCompanyDuplicates(companyId, { name: form.name, legalName: form.legalName, registrationNumber: form.registrationNumber, taxNumber: form.taxNumber, website: form.website, phone: form.phone, excludeId: partyId }) : await checkCrmContactDuplicates(companyId, { email: form.email, phone: form.phone || form.mobile, firstName: form.firstName, lastName: form.lastName, crmCompanyId: form.crmCompanyId, excludeId: partyId }); if (result.data.length) { setDuplicates(result.data); return; } } mutation.mutate(override); };
  const types = kind === 'company' ? catalog.data?.companyTypes ?? [] : catalog.data?.contactTypes ?? [];
  return <div><PageHeader title={`${edit ? 'Edit' : 'Add'} CRM ${kind}`} description={kind === 'company' ? 'External party master record; one company can have several relationship types.' : 'Contacts may belong to a CRM company or remain independent.'} />
    {error ? <div className="mb-4"><Alert>{error}</Alert></div> : null}{duplicates.length ? <div className="mb-4"><Alert tone="info"><p className="font-medium">Possible duplicate {kind} found.</p><ul className="mt-1 list-disc pl-5">{duplicates.map((x) => <li key={x.id}>{x.name || `${x.firstName} ${x.lastName ?? ''}`}</li>)}</ul><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={() => setDuplicates([])}>Review</Button><Button onClick={() => void submit(true)}>Continue anyway</Button></div></Alert></div> : null}
    <form className="space-y-5" onSubmit={(e) => { e.preventDefault(); void submit(); }}><section className={panel}><h2 className="mb-4 font-semibold">{kind === 'company' ? 'Company information' : 'Contact information'}</h2><div className="grid gap-4 md:grid-cols-2">
      {kind === 'company' ? <><Input label="Company name *" value={form.name} onChange={(e) => set('name', e.target.value)} /><Input label="Legal name" value={form.legalName} onChange={(e) => set('legalName', e.target.value)} /><Input label="Registration number" value={form.registrationNumber} onChange={(e) => set('registrationNumber', e.target.value)} /><Input label="Tax / VAT / NTN number" value={form.taxNumber} onChange={(e) => set('taxNumber', e.target.value)} /><Input label="Industry" value={form.industry} onChange={(e) => set('industry', e.target.value)} /></> : <><Input label="First name *" value={form.firstName} onChange={(e) => set('firstName', e.target.value)} /><Input label="Last name" value={form.lastName} onChange={(e) => set('lastName', e.target.value)} /><Input label="Job title" value={form.jobTitle} onChange={(e) => set('jobTitle', e.target.value)} /><Input label="Department" value={form.department} onChange={(e) => set('department', e.target.value)} /><Select label="Company" value={form.crmCompanyId} onChange={(e) => set('crmCompanyId', e.target.value)} options={[{ value: '', label: 'Independent contact' }, ...(companies.data ?? []).map((x) => ({ value: x.id, label: x.name }))]} /></>}
      <Input label="Email" type="email" value={form.email} onChange={(e) => set('email', e.target.value)} /><Input label={kind === 'contact' ? 'Alternate email' : 'Website'} type={kind === 'contact' ? 'email' : 'url'} value={kind === 'contact' ? form.alternateEmail : form.website} onChange={(e) => set(kind === 'contact' ? 'alternateEmail' : 'website', e.target.value)} /><Input label="Phone" value={form.phone} onChange={(e) => set('phone', e.target.value)} /><Input label={kind === 'company' ? 'Alternate phone' : 'Mobile'} value={kind === 'company' ? form.alternatePhone : form.mobile} onChange={(e) => set(kind === 'company' ? 'alternatePhone' : 'mobile', e.target.value)} />
      {kind === 'contact' ? <><Input label="WhatsApp" value={form.whatsapp} onChange={(e) => set('whatsapp', e.target.value)} /><Input label="Website" type="url" value={form.website} onChange={(e) => set('website', e.target.value)} /><Input label="LinkedIn" type="url" value={form.linkedin} onChange={(e) => set('linkedin', e.target.value)} /></> : null}
      <Input label="Address" value={form.address} onChange={(e) => set('address', e.target.value)} /><Input label="City" value={form.city} onChange={(e) => set('city', e.target.value)} /><Input label="Country code" maxLength={2} value={form.country} onChange={(e) => set('country', e.target.value.toUpperCase())} />{kind === 'company' ? <Input label="Postal code" value={form.postalCode} onChange={(e) => set('postalCode', e.target.value)} /> : null}
      <Select label="Status" value={form.status} onChange={(e) => set('status', e.target.value)} options={(kind === 'company' ? ['ACTIVE', 'INACTIVE', 'PROSPECT', 'BLOCKED'] : ['ACTIVE', 'INACTIVE', 'BLOCKED']).map((x) => ({ value: x, label: x }))} /><Select label="Assigned to" value={form.assignedToId} onChange={(e) => set('assignedToId', e.target.value)} options={[{ value: '', label: 'Unassigned' }, ...(assignees.data ?? []).map((x) => ({ value: x.id, label: `${x.user.firstName} ${x.user.lastName}` }))]} />
    </div><label className="mt-4 block"><span className="text-sm font-medium text-slate-700">{kind === 'company' ? 'Description' : 'Notes'}</span><textarea className="mt-1 min-h-24 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" value={kind === 'company' ? form.description : form.notesText} onChange={(e) => set(kind === 'company' ? 'description' : 'notesText', e.target.value)} /></label></section>
    <section className={panel}><h2 className="mb-3 font-semibold">{kind === 'company' ? 'Relationship types' : 'Contact roles'}</h2><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{types.map((x) => <label key={x.id} className="flex items-center gap-2 rounded-md border border-slate-200 p-3 text-sm"><input type="checkbox" checked={form.typeIds.includes(x.id)} onChange={() => toggle(x.id)} />{x.name}</label>)}</div></section>
    <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save'}</Button></div></form>
  </div>;
}
