import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, FileText, Pencil, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useToast } from '../../components/feedback/Toast';
import { Alert } from '../../components/ui/Alert';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { PageHeader } from '../../components/ui/PageHeader';
import { Select } from '../../components/ui/Select';
import { userErrorMessage } from '../../lib/api-client';
import { addCompanyAttachment, addCompanyNote, addContactAttachment, addContactNote, deleteCrmCompany, deleteCrmContact, getCompanyTimeline, getContactTimeline, getCrmCompany, getCrmContact, setPrimaryContact, type CrmCompany, type CrmContact } from '../../services/crm.service';

const panel = 'rounded-lg border border-slate-200 bg-white p-5';
const field = (label: string, value?: string | null) => <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value || '—'}</dd></div>;

export function PartyDetailPage({ kind }: { kind: 'company' | 'contact' }) {
  const { companyId = '', partyId = '' } = useParams(); const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast(); const [note, setNote] = useState(''); const [fileId, setFileId] = useState(''); const [fileTitle, setFileTitle] = useState(''); const [primaryContactId, setPrimaryContactId] = useState(''); const [purpose, setPurpose] = useState('BUSINESS');
  const party = useQuery({ queryKey: ['crm-party', kind, companyId, partyId], queryFn: async () => kind === 'company' ? (await getCrmCompany(companyId, partyId)).data : (await getCrmContact(companyId, partyId)).data, enabled: Boolean(companyId && partyId) });
  const timeline = useQuery({ queryKey: ['crm-party-timeline', kind, companyId, partyId], queryFn: async () => kind === 'company' ? (await getCompanyTimeline(companyId, partyId)).data : (await getContactTimeline(companyId, partyId)).data, enabled: Boolean(companyId && partyId) });
  const action = useMutation({ mutationFn: (job: () => Promise<unknown>) => job(), onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['crm-party', kind, companyId, partyId] }), qc.invalidateQueries({ queryKey: ['crm-party-timeline', kind, companyId, partyId] }), qc.invalidateQueries({ queryKey: ['crm-parties'] })]); toast.success('CRM record updated.'); }, onError: (e) => toast.error(userErrorMessage(e)) });
  if (party.isLoading) return <p className="text-sm text-slate-500">Loading…</p>; if (party.isError || !party.data) return <Alert>{userErrorMessage(party.error)}</Alert>;
  const isCompany = kind === 'company'; const company = party.data as CrmCompany; const contact = party.data as CrmContact; const title = isCompany ? company.name : `${contact.firstName} ${contact.lastName ?? ''}`; const notes = party.data.notes ?? []; const attachments = party.data.attachments ?? [];
  const addNote = () => { if (!note.trim()) return; action.mutate(async () => { if (isCompany) await addCompanyNote(companyId, partyId, note); else await addContactNote(companyId, partyId, note); setNote(''); }); };
  const addFile = () => { if (!fileId) return; action.mutate(async () => { if (isCompany) await addCompanyAttachment(companyId, partyId, { fileId, title: fileTitle || undefined }); else await addContactAttachment(companyId, partyId, { fileId, title: fileTitle || undefined }); setFileId(''); setFileTitle(''); }); };
  const remove = () => { if (!window.confirm(`Archive this CRM ${kind}?`)) return; action.mutate(async () => { if (isCompany) await deleteCrmCompany(companyId, partyId); else await deleteCrmContact(companyId, partyId); navigate(`/companies/${companyId}/crm/${isCompany ? 'companies' : 'contacts'}`); }); };
  return <div><Link to={`/companies/${companyId}/crm/${isCompany ? 'companies' : 'contacts'}`} className="mb-3 inline-flex items-center gap-1 text-sm text-slate-600"><ArrowLeft className="h-4 w-4" />Back</Link><PageHeader title={title} description={isCompany ? company.legalName || 'External CRM company' : contact.jobTitle || 'CRM contact'} actions={<><Link to={`/companies/${companyId}/crm/${isCompany ? 'companies' : 'contacts'}/${partyId}/edit`}><Button variant="secondary"><Pencil className="h-4 w-4" />Edit</Button></Link><Button variant="danger" onClick={remove}><Trash2 className="h-4 w-4" />Archive</Button></>} />
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><div className="mb-4 flex flex-wrap gap-2"><Badge tone={party.data.status === 'ACTIVE' ? 'green' : party.data.status === 'BLOCKED' ? 'red' : 'amber'}>{party.data.status}</Badge>{party.data.types.map((x) => <Badge key={x.id}>{x.type.name}</Badge>)}</div><dl className="grid gap-4 sm:grid-cols-2">{isCompany ? <>{field('Legal name', company.legalName)}{field('Registration', company.registrationNumber)}{field('Tax / VAT / NTN', company.taxNumber)}{field('Industry', company.industry)}{field('Phone', company.phone)}{field('Email', company.email)}{field('Website', company.website)}{field('Location', [company.city, company.country].filter(Boolean).join(', '))}</> : <>{field('Company', contact.crmCompany?.name || 'Independent')}{field('Job title', contact.jobTitle)}{field('Department', contact.department)}{field('Email', contact.email)}{field('Phone', contact.phone)}{field('Mobile', contact.mobile)}{field('WhatsApp', contact.whatsapp)}{field('Location', [contact.city, contact.country].filter(Boolean).join(', '))}</>}</dl></section>
      <section className={panel}><h2 className="mb-4 font-semibold">{isCompany ? 'Contacts' : 'Related leads'}</h2>{isCompany ? <><Link to={`/companies/${companyId}/crm/contacts/new`}><Button variant="secondary"><Plus className="h-4 w-4" />Add contact</Button></Link><div className="mt-3 space-y-2">{company.contacts?.map((x) => <Link key={x.id} to={`/companies/${companyId}/crm/contacts/${x.id}`} className="block rounded-md border border-slate-200 p-3 hover:bg-slate-50"><p className="font-medium">{x.firstName} {x.lastName}</p><p className="text-xs text-slate-500">{x.jobTitle || x.email || '—'}</p></Link>)}{!company.contacts?.length ? <p className="text-sm text-slate-500">No contacts linked.</p> : null}</div></> : <div className="space-y-2">{contact.leads?.map((x) => <Link key={x.id} to={`/companies/${companyId}/crm/leads/${x.id}`} className="block rounded-md border border-slate-200 p-3"><p className="font-medium text-primary-700">{x.leadNumber} · {x.name}</p><p className="text-xs text-slate-500">{x.status}</p></Link>)}{!contact.leads?.length ? <p className="text-sm text-slate-500">No related leads.</p> : null}</div>}</section>
      {isCompany ? <section className={panel}><h2 className="mb-3 font-semibold">Primary contacts by purpose</h2><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Select aria-label="Primary purpose" value={purpose} onChange={(e) => setPurpose(e.target.value)} options={['BUSINESS', 'ACCOUNTS', 'TECHNICAL', 'PROCUREMENT', 'OTHER'].map((x) => ({ value: x, label: x }))} /><Select aria-label="Primary contact" value={primaryContactId} onChange={(e) => setPrimaryContactId(e.target.value)} options={[{ value: '', label: 'Select contact' }, ...(company.contacts ?? []).map((x) => ({ value: x.id, label: `${x.firstName} ${x.lastName ?? ''}` }))]} /><Button disabled={!primaryContactId} onClick={() => action.mutate(() => setPrimaryContact(companyId, partyId, { crmContactId: primaryContactId, purpose }))}>Set</Button></div><div className="mt-3 space-y-2">{company.primaryContacts.map((x) => <div key={x.id} className="rounded-md bg-slate-50 p-3 text-sm"><strong>{x.purpose}:</strong> {x.crmContact.firstName} {x.crmContact.lastName}</div>)}</div></section> : null}
      <section className={panel}><h2 className="mb-3 font-semibold">Internal notes</h2><div className="flex gap-2"><textarea aria-label="New note" className="min-h-20 flex-1 rounded-md border border-slate-300 p-2 text-sm" value={note} onChange={(e) => setNote(e.target.value)} /><Button disabled={!note.trim()} onClick={addNote}>Add</Button></div><div className="mt-3 space-y-2">{notes.map((x) => <div key={x.id} className="rounded-md bg-slate-50 p-3"><p className="whitespace-pre-wrap text-sm">{x.note}</p><p className="mt-1 text-xs text-slate-500">{new Date(x.createdAt).toLocaleString()}</p></div>)}{!notes.length ? <p className="text-sm text-slate-500">No notes yet.</p> : null}</div></section>
      <section className={panel}><h2 className="mb-3 font-semibold">Documents</h2><Alert tone="info">Attach an existing secure FileObject from the shared storage system.</Alert><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label="File ID" placeholder="File UUID" value={fileId} onChange={(e) => setFileId(e.target.value)} /><Input aria-label="Title" placeholder="Title" value={fileTitle} onChange={(e) => setFileTitle(e.target.value)} /><Button disabled={!fileId} onClick={addFile}>Attach</Button></div><div className="mt-3 space-y-2">{attachments.map((x) => <a key={x.id} href={x.file.publicUrl || '#'} className="flex items-center gap-2 rounded-md border border-slate-200 p-3"><FileText className="h-4 w-4" />{x.title || x.file.originalName}</a>)}{!attachments.length ? <p className="text-sm text-slate-500">No documents attached.</p> : null}</div></section>
      {isCompany ? <section className={panel}><h2 className="mb-3 font-semibold">Related leads</h2><div className="space-y-2">{company.leads?.map((x) => <Link key={x.id} to={`/companies/${companyId}/crm/leads/${x.id}`} className="block rounded-md border border-slate-200 p-3 text-sm text-primary-700">{x.leadNumber} · {x.name}</Link>)}{!company.leads?.length ? <p className="text-sm text-slate-500">No related leads.</p> : null}</div></section> : null}
      <section className={panel}><h2 className="mb-3 font-semibold">Future modules</h2><p className="text-sm text-slate-500">Opportunities, tenders, contracts and project party relationships will appear here when those modules are implemented.</p></section>
    </div>
    <section className={`${panel} mt-5`}><h2 className="mb-4 font-semibold">Timeline</h2><ol className="space-y-3">{timeline.data?.map((x) => <li key={x.id} className="border-l-2 border-primary-200 pl-3"><p className="text-sm font-medium">{x.action.replaceAll('.', ' · ')}</p><p className="text-xs text-slate-500">{new Date(x.createdAt).toLocaleString()} {x.user ? `· ${x.user.firstName} ${x.user.lastName}` : ''}</p></li>)}</ol></section>
  </div>;
}
