export const PERMISSIONS = {
  COMPANY_VIEW: 'Company.View',
  COMPANY_CREATE: 'Company.Create',
  COMPANY_UPDATE: 'Company.Update',
  COMPANY_DELETE: 'Company.Delete',
  COMPANY_SETTINGS: 'Company.Settings',
  DEPARTMENT_MANAGE: 'Department.Manage',
  BRANCH_MANAGE: 'Branch.Manage',
  DESIGNATION_MANAGE: 'Designation.Manage',
  COST_CENTER_MANAGE: 'CostCenter.Manage',
  BUSINESS_UNIT_MANAGE: 'BusinessUnit.Manage',
  REGION_MANAGE: 'Region.Manage',
  TEAM_MANAGE: 'Team.Manage',
  REPORTING_HIERARCHY_MANAGE: 'ReportingHierarchy.Manage',
  PROJECT_VIEW: 'Project.View',
  PROJECT_CREATE: 'Project.Create',
  PROJECT_EDIT: 'Project.Edit',
  PROJECT_DELETE: 'Project.Delete',
  PROJECT_ASSIGN: 'Project.Assign',
  PROJECT_SETTINGS: 'Project.Settings',
  PROJECT_CLOSE: 'Project.Close',
  PROJECT_APPROVE: 'Project.Approve',
  PROJECT_PLANNING_VIEW: 'ProjectPlanning.View',
  PROJECT_PLANNING_CREATE: 'ProjectPlanning.Create',
  PROJECT_PLANNING_EDIT: 'ProjectPlanning.Edit',
  PROJECT_PLANNING_DELETE: 'ProjectPlanning.Delete',
  SCHEDULE_EDIT: 'Schedule.Edit',
  SCHEDULE_RECALCULATE: 'Schedule.Recalculate',
  GANTT_VIEW: 'Gantt.View',
  GANTT_EDIT: 'Gantt.Edit',
  BASELINE_VIEW: 'Baseline.View',
  BASELINE_CREATE: 'Baseline.Create',
  BASELINE_APPROVE: 'Baseline.Approve',
  PROGRESS_UPDATE: 'Progress.Update',
  PROGRESS_VIEW: 'Progress.View',
  EMPLOYEE_VIEW: 'Employee.View',
  EMPLOYEE_CREATE: 'Employee.Create',
  EMPLOYEE_EDIT: 'Employee.Edit',
  EMPLOYEE_DELETE: 'Employee.Delete',
  EMPLOYEE_DOCUMENTS: 'Employee.Documents',
  EMPLOYEE_ASSIGN_PROJECT: 'Employee.AssignProject',
  EMPLOYEE_TRANSFER: 'Employee.Transfer',
  EMPLOYEE_EXPORT: 'Employee.Export',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
